// svelte/src/lib/EditorComponent.svelte
<script lang="ts">
	import CursorComponent from './CursorComponent.svelte';
	import DiagnosticComponent from './DiagnosticComponent.svelte';

	import { SourceText } from '../../../../parser/ng';
	import { onMount } from 'svelte';
	import type { Position } from './Position';

	const code = `A1 :: A4
A5 :: A2
A2 :: A1+3
A3 :: A2+5
A4 :: A3+A2+A5
A3 :: 1
`;

	const text = $state(code);
	const tree = $derived(SourceText.parse(text));
	const lines = $derived(tree.getLines());
	const diagnostics = $derived(tree.diagnosticsBag.diagnostics);

	let renderCursor = $state(false);
	let cursor = $state(0);
	let line = $derived(tree.getLine(cursor));
	let column = $derived(tree.getColumn(cursor));
	let x = $state(0);
	let y = $state(0);
	// svelte-ignore state_referenced_locally
	let prevColumn = column;

	function handleKey(event: KeyboardEvent) {
		const input = event.key;
		if (input === 'ArrowRight') {
			event.preventDefault();
			tranformCaretX();
		} else if (input === 'ArrowLeft') {
			event.preventDefault();
			tranformCaretX(-1);
		} else if (input === 'ArrowDown') {
			event.preventDefault();
			tranformCaretY();
		} else if (input === 'ArrowUp') {
			event.preventDefault();
			tranformCaretY(-1);
		}
	}

	function updatePosition() {
		const pos = getPosition(line, column);
		x = pos.x;
		y = pos.y;
	}

	function tranformCaretX(step = 1) {
		const newPos = cursor + step;
		if (newPos >= 0 && newPos <= text.length) {
			cursor = newPos;
			prevColumn = column;
		}
	}

	function tranformCaretY(steps = 1) {
		const prevLine = line + steps;
		if (prevLine > 0) {
			const pos = tree.getPosition(prevLine, prevColumn);
			cursor = pos;
		} else {
			prevColumn = 1;
			cursor = 0;
		}
	}

	function getPosition(line: number, column: number): Position {
		const lineElement = document.getElementById(`line-${line}`)!;
		let charCount = 0;
		column--;
		for (const child of Array.from(lineElement.childNodes)) {
			const range = document.createRange();
			try {
				if (child.nodeType === Node.ELEMENT_NODE) {
					const span = child as HTMLElement;
					const spanText = span.textContent || '';
					const spanLength = spanText.length;
					if (charCount + spanLength >= column) {
						const offsetInSpan = column - charCount;
						range.setStart(span.firstChild!, offsetInSpan);
						range.setEnd(span.firstChild!, offsetInSpan);
						return getCursorPositionFromRange(range);
					}
					charCount += spanLength;
				} else if (child.nodeType === Node.TEXT_NODE) {
					const textNode = child as Text;
					const textLength = textNode.textContent?.length || 0;
					if (charCount + textLength >= column) {
						const offsetInText = column - charCount;
						range.setStart(textNode, offsetInText);
						range.setEnd(textNode, offsetInText);
						return getCursorPositionFromRange(range);
					}
					charCount += textLength;
				}
			} finally {
				range.detach();
			}
		}
		const lastElement = lineElement.lastElementChild as HTMLElement;
		const rect = lastElement.getBoundingClientRect();
		return { x: rect.right, y: rect.top, height: rect.height };
	}

	function getCursorPositionFromRange(range: Range): Position {
		const rect = range.getBoundingClientRect();
		return { x: rect.x, y: rect.y, height: rect.height };
	}

	onMount(() => {
		renderCursor = true;
	});

	$effect(() => updatePosition());
</script>

<div class="editor">
	<h2>Todo</h2>
	✔ update position on window resize
	<br />
	✘ render diagnostic spans on top of the text
	<br />
	✘ edit text on keyboard event
	<br />
	✘ blinking cursor animation
	<br />

	<br />

	<div class="space">
		{#each lines as line, index}
			<div id={`line-${index + 1}`} class="line">
				{#each line.getTokens() as token}
					{#if token.span.text}
						<span class={token.class}>
							{token.span.text}
						</span>
					{:else}
						<span class={token.class}> &nbsp; </span>
					{/if}
				{/each}
			</div>
		{/each}
		{#if renderCursor}
			<CursorComponent {x} {y} />
		{/if}
	</div>
	<div class="stats">
		line {line} column {column}
	</div>

	<div class="diagnostics">
		{#each diagnostics as diagnostic}
			<span>{diagnostic.message}</span>
		{/each}
	</div>

	{#if renderCursor}
		{#each diagnostics as diagnostic}
			<DiagnosticComponent
				from={getPosition(diagnostic.span.line, diagnostic.span.column)}
				to={getPosition(diagnostic.span.line, diagnostic.span.column + diagnostic.span.length)}
			/>
		{/each}
	{/if}
</div>

<svelte:window on:keydown={handleKey} on:resize={updatePosition} on:scroll={updatePosition} />

<style scoped>
	.editor {
		display: flex;
		margin: auto;
		margin-top: auto;
		flex-direction: column;
		width: fit-content;
		height: fit-content;
		border: 1px solid lightseagreen;
		padding: 10px;
		font-family: SuisseIntl-Regular, Helvetica, Arial, sans-serif;
		font-size: 14px;
	}
	.space {
		width: 700px;
	}
	.line {
		display: flex;
		flex-direction: row;
		min-height: 16px;
		border: 1px solid transparent;
		box-sizing: border-box;
	}
	span {
		display: flex;
		height: fit-content;
		width: fit-content;
		box-sizing: border-box;
		padding: 0;
		margin: 0;
		min-width: 3px;
		min-height: 17px;
		box-sizing: border-box;
		white-space: pre;
	}
	.end-of-file-token,
	.line-break-trivia,
	.space-trivia {
		display: inline-block;
		width: 1px;
		height: 1em;
	}
	.stats {
		margin-top: 20px;
	}
	.diagnostics {
		margin-top: 20px;
	}
	.space {
		border: 1px solid lightseagreen;
	}
</style>

// ui/angular/src/app/editor/editor.component.ts
import { Component, Input, signal, computed, HostListener, effect, Inject, PLATFORM_ID, Output, EventEmitter, AfterViewInit } from "@angular/core";
import { CursorComponent } from "./cursor/cursor.component";
import { DOCUMENT, NgClass, isPlatformBrowser } from "@angular/common";
import { SourceText } from "../../../../../src/lexing/source.text";

// var text = `A1 :: A3
//   A2 :: A1
//    A3 :: A2
// A4 :: A3
//   A1 :: A4
// `;

// this test case is problematic
var text = `A1 :: A4
A5 :: A2
A2 :: A1+3
A3 :: A2+5
A4 :: A3+A2+A5
A3 :: 1
`;

export interface Position {
  x: number;
  y: number;
  height: number;
}

export interface DiagnosticWithPosition {
  from: Position;
  to: Position;
}

@Component({
  selector: "app-editor",
  standalone: true,
  imports: [CursorComponent, NgClass],
  templateUrl: "./editor.component.html",
  styleUrl: "./editor.component.scss",
})
export class EditorComponent implements AfterViewInit {
  @Input()
  text = text;
  length = text.length;
  code = signal(text);
  source = computed(() => SourceText.parse(this.code()));
  lines = computed(() => this.source().getLines());
  cursor = signal(this.text.length);
  line = computed(() => this.source().getLine(this.cursor()).number);
  column = computed(() => this.source().getColumn(this.cursor()));
  cursorX = 0;
  cursorY = 0;
  caretWidth = 4;
  prevColumn = this.line();
  diagnostics = computed(() => this.source().diagnosticsBag.diagnostics);
  @Output("diagnostics") emitDiagnosticsPositions = new EventEmitter<DiagnosticWithPosition[]>();

  constructor(@Inject(DOCUMENT) private document: Document, @Inject(PLATFORM_ID) private platformId: Object) {
    effect(
      () => {
        const current = this.code().length;
        const change = current - this.length;
        this.cursor.update((pos) => (pos + change >= 0 ? pos + change : 0));
        this.length = current;
      },
      {
        allowSignalWrites: true,
      }
    );
    if (isPlatformBrowser(this.platformId)) {
      effect(() => {
        const line = this.line();
        const column = this.column();
        setTimeout(() => this.renderPosition(line, column));
        this.emitDiagnosticPositions();
      });
    }
  }

  @HostListener("window:scroll")
  @HostListener("window:resize")
  onWindowChange() {
    this.renderPosition(this.line(), this.column());
    this.emitDiagnosticPositions();
  }

  private renderPosition(line: number, column: number) {
    const pos = this.getPosition(line, column);
    this.cursorX = pos.x;
    this.cursorY = pos.y;
  }

  emitDiagnosticPositions() {
    setTimeout(() => {
      if (isPlatformBrowser(this.platformId)) {
        const positions = this.diagnostics().map((d) => ({ from: this.getPosition(d.span.line, d.span.column), to: this.getPosition(d.span.line, d.span.column + d.span.length) }));
        this.emitDiagnosticsPositions.emit(positions);
      }
    });
  }

  ngAfterViewInit() {
    this.emitDiagnosticPositions();
  }

  @HostListener("window:keydown", ["$event"])
  handleKey(event: KeyboardEvent) {
    const input = event.key as string;
    if (event.ctrlKey && input === "x") {
      this.removeLine();
    } else if (input === "ArrowRight") {
      event.preventDefault();
      this.tranformCaretX();
    } else if (input === "ArrowLeft") {
      event.preventDefault();
      this.tranformCaretX(-1);
    } else if (input === "ArrowUp") {
      event.preventDefault();
      this.transformCaretY(-1);
    } else if (input === "ArrowDown") {
      event.preventDefault();
      this.transformCaretY();
    } else if (input === "Enter") {
      this.insertText();
    } else if (input === "Tab") {
      event.preventDefault();
      this.insertText("\t");
    } else if (input === "Backspace") {
      this.removeText();
    } else if (input === "Delete" && this.cursor() !== this.length) {
      this.deleteText();
    } else if (input.length === 1 && !event.ctrlKey && !event.altKey) {
      event.preventDefault();
      this.insertText(input);
    }
  }

  private deleteText() {
    this.tranformCaretX();
    this.removeText();
  }

  private removeLine() {
    const ln = this.line() - 1;
    if (ln >= 0) {
      const line = this.lines()[ln];
      const text = this.code().slice(0, line.span.start) + this.code().slice(line.span.end);
      this.code.set(text);
      setTimeout(() => {
        this.cursor.set(line.span.start);
        this.deleteText();
      });
    }
  }

  private insertText(charText: string = "\n") {
    const text = this.code();
    const pos = this.cursor();
    const newText = text.substring(0, pos) + charText + text.substring(pos);
    this.code.set(newText);
  }

  private removeText() {
    const text = this.code();
    const pos = this.cursor();
    const newText = text.substring(0, pos - 1) + text.substring(pos);
    this.code.set(newText);
  }

  private tranformCaretX(steps: number = 1) {
    const pos = this.cursor();
    const newPos = pos + steps;
    if (newPos >= 0 && newPos <= this.length) {
      this.cursor.set(newPos);
      this.prevColumn = this.column();
    }
  }

  transformCaretY(steps: number = 1) {
    const prevLine = this.line() + steps;
    if (prevLine > 0) {
      const pos = this.source().getPosition(prevLine, this.prevColumn);
      this.cursor.set(pos);
    } else {
      this.prevColumn = 1;
      this.cursor.set(0);
    }
  }

  protected getPosition(line: number, column: number): Position {
    const lineElement = this.document.getElementById(`row-${line}`)!; // Non-null assertion.
    let charCount = 0;
    column--;
    for (const child of Array.from(lineElement.childNodes)) {
      const range = this.document.createRange();
      try {
        if (child.nodeType === Node.ELEMENT_NODE) {
          const span = child as HTMLElement;
          const spanText = span.textContent || "";
          const spanLength = spanText.length;
          if (charCount + spanLength >= column) {
            const offsetInSpan = column - charCount;
            range.setStart(span.firstChild!, offsetInSpan);
            range.setEnd(span.firstChild!, offsetInSpan);
            return this.getCursorPositionFromRange(range);
          }
          charCount += spanLength;
        } else if (child.nodeType === Node.TEXT_NODE) {
          const textNode = child as Text;
          const textLength = textNode.textContent?.length || 0;
          if (charCount + textLength >= column) {
            const offsetInText = column - charCount;
            range.setStart(textNode, offsetInText);
            range.setEnd(textNode, offsetInText);
            return this.getCursorPositionFromRange(range);
          }
          charCount += textLength;
        }
      } finally {
        range.detach();
      }
    }
    const lastElement = lineElement.lastElementChild as HTMLElement;
    const rect = lastElement.getBoundingClientRect();
    return { x: rect.right, y: rect.top, height: rect.height };
  }

  private getCursorPositionFromRange(range: Range): Position {
    const rect = range.getBoundingClientRect();
    return { x: rect.x, y: rect.y, height: rect.height };
  }

  protected isActive(ln: number): any {
    return ln + 1 === this.line();
  }
}
