// angular/src/app/editor/editor.component.ts
import { Component, Input, signal, computed, HostListener, effect, Inject, PLATFORM_ID } from "@angular/core";
import { CursorComponent } from "./cursor/cursor.component";
import { DOCUMENT, NgClass, isPlatformBrowser } from "@angular/common";

import { SourceText } from "../../../../ng";

// var text = `A1 :: A3
//   A2 :: A1
//    A3 :: A2
// A4 :: A3
//   A1 :: A4
// `;

// this test case is problematic
var text = `A1 :: A4
A5 :: A2
A2 :: A1+3
A3 :: A2+5
A4 :: A3+A2+A5
A3 :: 1
`;

@Component({
  selector: "app-editor",
  standalone: true,
  imports: [CursorComponent, NgClass],
  templateUrl: "./editor.component.html",
  styleUrl: "./editor.component.scss",
})
export class EditorComponent {
  @Input()
  text = text;
  length = text.length;
  code = signal(text);
  source = computed(() => SourceText.parse(this.code()));
  lines = computed(() => this.source().getLines());
  cursor = signal(this.text.length);
  line = computed(() => this.source().getLine(this.cursor()));
  column = computed(() => this.source().getColumn(this.cursor()));
  cursorX = 0;
  cursorY = 0;
  caretWidth = 4;
  prevColumn = this.line();
  diagnostics = computed(() => this.source().diagnostics.getDiagnostics());
  error = computed(() => this.diagnostics().length);

  constructor(@Inject(DOCUMENT) private document: Document, @Inject(PLATFORM_ID) private platformId: Object) {
    effect(
      () => {
        const current = this.code().length;
        const change = current - this.length;
        this.cursor.update((pos) => (pos + change >= 0 ? pos + change : 0));
        this.length = current;
      },
      {
        allowSignalWrites: true,
      }
    );
    if (isPlatformBrowser(this.platformId)) {
      effect(() => {
        const line = this.line();
        const column = this.column();
        setTimeout(() => this.renderPosition(line, column));
      });
    }
  }

  @HostListener("window:scroll")
  @HostListener("window:resize")
  onWindowChange() {
    const line = this.line();
    const column = this.column();
    this.renderPosition(line, column);
  }

  private renderPosition(line: number, column: number) {
    const pos = this.getPosition(line, column);
    this.cursorX = pos.cursorX;
    this.cursorY = pos.cursorY;
  }

  @HostListener("window:keydown", ["$event"])
  handleKey(event: KeyboardEvent) {
    const input = event.key as string;
    if (event.ctrlKey && input === "x") {
      this.removeLine();
    } else if (input === "ArrowRight") {
      event.preventDefault();
      this.tranformCaretX();
    } else if (input === "ArrowLeft") {
      event.preventDefault();
      this.tranformCaretX(-1);
    } else if (input === "ArrowUp") {
      event.preventDefault();
      this.transformCaretY(-1);
    } else if (input === "ArrowDown") {
      event.preventDefault();
      this.transformCaretY();
    } else if (input === "Enter") {
      this.insertText();
    } else if (input === "Tab") {
      event.preventDefault();
      this.insertText("\t");
    } else if (input === "Backspace") {
      this.removeText();
    } else if (input === "Delete" && this.cursor() !== this.length) {
      this.deleteText();
    } else if (input.length === 1 && !event.ctrlKey && !event.altKey) {
      event.preventDefault();
      this.insertText(input);
    }
  }

  private deleteText() {
    this.tranformCaretX();
    this.removeText();
  }

  private removeLine() {
    const ln = this.line() - 1;
    if (ln >= 0) {
      const line = this.lines()[ln];
      const text = this.code().slice(0, line.span.start) + this.code().slice(line.span.end);
      this.code.set(text);
      setTimeout(() => {
        this.cursor.set(line.span.start);
        this.deleteText();
      });
    }
  }

  private insertText(charText: string = "\n") {
    const text = this.code();
    const pos = this.cursor();
    const newText = text.substring(0, pos) + charText + text.substring(pos);
    this.code.set(newText);
  }

  private removeText() {
    const text = this.code();
    const pos = this.cursor();
    const newText = text.substring(0, pos - 1) + text.substring(pos);
    this.code.set(newText);
  }

  private tranformCaretX(steps: number = 1) {
    const pos = this.cursor();
    const newPos = pos + steps;
    if (newPos >= 0 && newPos <= this.length) {
      this.cursor.set(newPos);
      this.prevColumn = this.column();
    }
  }

  transformCaretY(steps: number = 1) {
    const prevLine = this.line() + steps;
    if (prevLine > 0) {
      const pos = this.source().getPosition(prevLine, this.prevColumn);
      this.cursor.set(pos);
    } else {
      this.prevColumn = 1;
      this.cursor.set(0);
    }
  }

  private getPosition(line: number, column: number): { cursorX: number; cursorY: number } {
    const lineElement = this.document.getElementById(`row-${line}`)!; // Non-null assertion.
    let charCount = 0;
    column--;
    for (const child of Array.from(lineElement.childNodes)) {
      const range = this.document.createRange();
      try {
        if (child.nodeType === Node.ELEMENT_NODE) {
          const span = child as HTMLElement;
          const spanText = span.textContent || "";
          const spanLength = spanText.length;
          if (charCount + spanLength >= column) {
            const offsetInSpan = column - charCount;
            range.setStart(span.firstChild!, offsetInSpan);
            range.setEnd(span.firstChild!, offsetInSpan);
            return this.getCursorPositionFromRange(range);
          }
          charCount += spanLength;
        } else if (child.nodeType === Node.TEXT_NODE) {
          const textNode = child as Text;
          const textLength = textNode.textContent?.length || 0;
          if (charCount + textLength >= column) {
            const offsetInText = column - charCount;
            range.setStart(textNode, offsetInText);
            range.setEnd(textNode, offsetInText);
            return this.getCursorPositionFromRange(range);
          }
          charCount += textLength;
        }
      } finally {
        range.detach();
      }
    }
    const lastElement = lineElement.lastElementChild as HTMLElement;
    const rect = lastElement.getBoundingClientRect();
    return { cursorX: rect.right, cursorY: rect.top };
  }

  private getCursorPositionFromRange(range: Range): { cursorX: number; cursorY: number } {
    const rect = range.getBoundingClientRect();
    return { cursorX: rect.x, cursorY: rect.y };
  }
}

<div style="display: flex; flex-direction: row">
  <div class="line-numbers">
    @for (lineSpan of lines(); track $index) {
    <div class="line-number">{{ $index + 1 }}</div>
    }
  </div>
  <div class="editor-space">
    @for (lineSpan of lines(); track $index) {
    <div
      class="line"
      [id]="'row-' + ($index + 1)"
      [ngClass]="{ active: $index + 1 === line() }"
    >
      @if (highlight()) { @for (token of lineSpan.getTokens(); track $index) {
      <span [class]="token.kind">{{ token.span.text || "&nbsp;" }}</span>
      } } @else {{{ lineSpan.span.text || "&nbsp;" }}
      }
    </div>

    }
    <div class="status-bar">line: {{ line() }} column: {{ column() }}</div>
    @if (diagnostics().length) {
    <div class="diagnostics">
      @for (d of diagnostics(); track $index) {
      <div class="diagnostic" [textContent]="d.viewMessage()"></div>
      }
    </div>

    }
  </div>
</div>
<div class="colors" (mousedown)="switchHighlight()">
  <svg
    xmlns="http://www.w3.org/2000/svg"
    height="20px"
    viewBox="0 -960 960 960"
    width="20px"
  >
    <path
      d="M480-80q-82 0-155-31.5t-127.5-86Q143-252 111.5-325T80-480q0-83 32.5-156t88-127Q256-817 330-848.5T488-880q80 0 151 27.5t124.5 76q53.5 48.5 85 115T880-518q0 115-70 176.5T640-280h-74q-9 0-12.5 5t-3.5 11q0 12 15 34.5t15 51.5q0 50-27.5 74T480-80Zm0-400Zm-220 40q26 0 43-17t17-43q0-26-17-43t-43-17q-26 0-43 17t-17 43q0 26 17 43t43 17Zm120-160q26 0 43-17t17-43q0-26-17-43t-43-17q-26 0-43 17t-17 43q0 26 17 43t43 17Zm200 0q26 0 43-17t17-43q0-26-17-43t-43-17q-26 0-43 17t-17 43q0 26 17 43t43 17Zm120 160q26 0 43-17t17-43q0-26-17-43t-43-17q-26 0-43 17t-17 43q0 26 17 43t43 17ZM480-160q9 0 14.5-5t5.5-13q0-14-15-33t-15-57q0-42 29-67t71-25h70q66 0 113-38.5T800-518q0-121-92.5-201.5T488-800q-136 0-232 93t-96 227q0 133 93.5 226.5T480-160Z"
    />
  </svg>
</div>
<app-cursor [x]="cursorX" [y]="cursorY" [width]="2" [height]="16"></app-cursor>

// svelte/src/lib/components/EditorComponent.svelte
<script lang="ts">
	import CursorComponent from './CursorComponent.svelte';
	import DiagnosticComponent from './DiagnosticComponent.svelte';

	import { SourceText } from '../../../../ng';
	import { onMount } from 'svelte';
	import { getPosition } from '../Position';

	const code = `A1 :: A4
A5 :: 2    
A2 :: A1+3
A 3 :: A2+5
A4 :: A3+A2+       A5
A3 :: 1

`;

	let text = $state(code);

	const tree = $derived(SourceText.parse(text));
	const lines = $derived(tree.getLines());
	const diagnostics = $derived(
		tree.diagnosticsBag.diagnostics
			.sort((a, b) => a.span.start - b.span.start)
			.sort((a, b) => a.span.start - b.span.start)
	);

	// svelte-ignore state_referenced_locally
	let cursor = $state(text.length);
	let line = $derived(tree.getLine(cursor));
	let column = $derived(tree.getColumn(cursor));
	let currentLine = $derived(tree.getLines()[line - 1]);
	let tokens = $derived(tree.getTokens());

	let x = $state(0);
	let y = $state(0);

	let renderCursor = $state(false);

	// svelte-ignore state_referenced_locally
	let prevColumn = column;

	function handleKey(event: KeyboardEvent) {
		renderCursor = true;
		const input = event.key;
		if (input === 'ArrowDown' && event.altKey) {
			event.preventDefault();
			moveLine(+1);
		} else if (input === 'ArrowUp' && event.altKey) {
			event.preventDefault();
			moveLine(-1);
		} else if (input === 'x' && event.ctrlKey) {
			event.preventDefault();
			removeLine();
		} else if (input === 'ArrowRight') {
			event.preventDefault();
			moveCursorX(+1);
		} else if (input === 'ArrowLeft') {
			event.preventDefault();
			moveCursorX(-1);
		} else if (input === 'ArrowDown') {
			event.preventDefault();
			moveCursorY(+1);
		} else if (input === 'ArrowUp') {
			event.preventDefault();
			moveCursorY(-1);
		} else if (input === 'Enter') {
			event.preventDefault();
			insertText();
		} else if (input === 'Backspace') {
			event.preventDefault();
			backspace();
		} else if (input === 'Delete') {
			event.preventDefault();
			moveCursorX(+1);
			removeText();
			moveCursorX(-1);
		} else if (input.length === 1 && !event.ctrlKey && !event.altKey) {
			event.preventDefault();
			insertText(input);
		}
	}

	function moveLine(step: number) {
		const nextLine = line + step;
		const nextTree = tree.swapLines(line, nextLine);
		if (!nextTree) return;
		text = nextTree;
		cursor = tree.getPosition(nextLine, prevColumn);
	}

	function backspace() {
		removeText();
		moveCursorX(-1);
	}

	function updatePosition() {
		const pos = getPosition(line, column);
		x = pos.x;
		y = pos.y;
	}

	function moveCursorX(step: number) {
		const newPos = cursor + step;
		if (newPos >= 0 && newPos <= text.length) {
			cursor = newPos;
			prevColumn = column;
		}
	}

	function moveCursorY(steps: number) {
		const prevLine = line + steps;
		if (prevLine > 0) {
			const pos = tree.getPosition(prevLine, prevColumn);
			cursor = pos;
		} else {
			prevColumn = 1;
			cursor = 0;
		}
	}

	function insertText(charText: string = '\n') {
		text = text.substring(0, cursor) + charText + text.substring(cursor);
		cursor += 1;
	}

	function removeText() {
		text = text.substring(0, cursor - 1) + text.substring(cursor);
	}

	function removeLine() {
		const span = currentLine.fullSpan;
		if (span.length === 0) {
			backspace();
		} else {
			text = text.slice(0, span.start) + text.slice(span.end);
			cursor = span.start;
		}
	}

	$effect(updatePosition);

	onMount(() => (renderCursor = true));
</script>

<div class="editor">
	<div class="todos">
		<div>frontend</div>
		<br />
		<div class="todo">
			<span class="check"> </span> add selection capability.
		</div>
		<div class="todo">
			<span class="check"> </span> render multiline diagnostic highlighters.
		</div>
		<div class="todo">
			<span class="check"> </span> copy and paste text from the clipboard.
		</div>
		<div class="todo">
			<span class="check"> </span> add line numbers.
		</div>
		<div class="todo">
			<span class="check"> </span> blinking cursor animation.
		</div>
	</div>
	<br />
	<br />
	<div
		class="space highlight"
		onfocus={() => (renderCursor = true)}
		onblur={() => (renderCursor = false)}
		tabindex="-1"
	>
		{#each lines as line, i}
			<span id={`line-${i + 1}`} class="line">
				{#each line.getTokens() as token, j}
					{#if token.span.length}
						<span class="token token-{(j % 4) + 1} {token.class}">
							{token.span.text}
						</span>
					{:else}
						<span class="token {token.class}">&nbsp;</span>
					{/if}
				{/each}
			</span>
		{/each}
		{#if renderCursor}
			<CursorComponent {x} {y} />
		{/if}
	</div>
	<br />
	<div class="stats">
		line {line} column {column}
	</div>
	{#if diagnostics.length}
		<div class="diagnostics highlight">
			{#each diagnostics as { message, span }}
				<div class="diagnostic">
					<div class="address">{span.address}</div>
					<div>{message}</div>
				</div>
			{/each}
		</div>
	{/if}
	{#each diagnostics as { span: { line, column, length }, message }}
		<DiagnosticComponent {line} {column} {length} {message} />
	{/each}
	<br />
	<br />
	{#if tokens.length > 1}
		<div>tokens</div>
		<br />
		<div class="tokens highlight">
			{#each tokens as token, i}
				<span class="token token-{(i % 4) + 1} {token.class}">{token.span.text}</span>
			{/each}
		</div>
	{/if}
</div>
<svelte:window on:keydown={handleKey} on:resize={updatePosition} on:scroll={updatePosition} />

<style scoped lang="scss">
	.highlight {
		background-color: #f7f7f8;
		outline: 1px solid #d9d9e3;
		border-radius: 7px;
		padding: 10px 20px;
	}
	.editor {
		display: flex;
		margin: auto;
		margin-top: auto;
		flex-direction: column;
		width: fit-content;
		padding: 10px;
		font-family: SuisseIntl-Regular, Helvetica, Arial, sans-serif;
		font-size: 14px;
		cursor: default;
	}
	.space {
		width: 700px;
	}
	.line {
		position: relative;
		display: flex;
		flex-direction: row;
		box-sizing: border-box;
		z-index: 1;
		pointer-events: none;
	}
	.tokens .space-trivia {
		background-color: #d9d9e3;
	}
	.stats {
		margin-top: 20px;
	}
	.diagnostics {
		display: flex;
		flex-direction: column;
		margin-top: 20px;
	}
	.diagnostic {
		display: flex;
		flex-direction: row;
		align-items: center;
		white-space: pre;
	}
	.todos {
		padding: 7px;
	}
	.todo {
		display: flex;
		flex-direction: row;
	}
	.check {
		display: flex;
		width: 17px;
		height: 17px;
		justify-content: center;
		align-items: center;
		margin-right: 10px;
	}
	.tokens {
		width: fit-content;
		display: flex;
		flex-direction: row;
	}
	.token {
		display: inline-block;
		width: fit-content;
		height: fit-content;
		min-width: 1px;
		white-space: pre;
	}
	.address {
		width: fit-content;
		min-width: 40px;
		margin-right: 6px;
	}
</style>
